version: '3'

services:
  service1:
    image: quote-server
    ports:
      - "5051:3030"
    networks:
      - my-network

  service2:
    image: quote-server
    ports:
      - "6061:3030"
    networks:
      - my-network

  service3:
    image: quote-server
    ports:
      - "7071:3030"
    networks:
      - my-network

networks:
  my-network:
    external: true
